variables:
  colors:
    primaryColor1: 3A3A3A
    primaryColor2: 5A5A5A
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
  fonts:
    defaultHeaderFont: georgia
    defaultBodyFont: helvetica
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'sites/kidsrestorethekepler/themes/custom/dsp1/logo.png'
favicon:
  use_default: true
  path: ''
omega_toggle_intro: 0
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 0
screen_demo_indicator: 0
default_layout: primary
home_layout: front
enable_omegags_layout: 1
layouts: {  }
breakpoint_group_primary: dsp1.standard
breakpoint_group_front: dsp1.standard
edit_this_layout: front
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_tags_layout: primary
