#!/bin/bash
##
## The script assumes a subdirectory structure under the theme of :
##
##  style -- sccs -- import
##        |- css
##
##



ippath=/var/www/vhosts/drupal-8.x/web/themes
if [ ! -d $ippath ]
then
	kdialog --sorry "Theme Base Directory incorrect.\nCheck script $0 \n\nScript will exit" --title "Whoops"
	exit
fi

DIR=$(pwd)
cd $ippath

themedir=$(kdialog --title "Choose theme to compile" --getexistingdirectory .)


if [ ! -d $themedir/style ] ; then
  kdialog --error "$themedir/style doesn't exist\nExiting" --title "Error"
  exit
fi
cd $themedir/style

if [ -d $themedir/style/scss/imports ]; then
  importsdir=$themedir/style/scss/imports
fi

if [ -f css_safe.tar.bz2 ]; then
	rm -f css_safe.tar.bz2
fi
tar -cjf css_safe.tar.bz2 css

for dir in $(find scss -type d -exec ls -1d {} \; )
  do
    if [ ! $dir = scss/imports ]; then
  	  for file in $( ls -1 $dir/*.scss )
  	  do
		c1=$(echo $file |  rev | cut -d'/' -f1 | rev |cut -c1)
		c5=$(echo $file |  rev | cut -d'/' -f1 | rev |cut -c1-5)
		if [ ! $c1 = _ -a ! $c5 = omega ] ; then 
		  cssfile=css/$(echo $file|cut -d'/' -f2-|cut -d'.' -f-1).css
		  #echo "/usr/bin/sass -t expanded -C -I "$importsdir $file $cssfile
		  /usr/bin/sass -t expanded -C -I $importsdir $file $cssfile
		fi
  	  done
  	fi
  done

   
cd $DIR
kdialog --title "Complete" --passivepopup "SCSS in:\n'$themedir'\ncompiled" 
